[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "alloc-many-collections"
publish = false
version = "0.0.0-alpha.0"

[dependencies]
alloc-many = { path = ".." }

[dev-dependencies]
alloc-many-bump = { path = "../bump" }
